language: node_js
node_js:
- 5.7.0
script:
- npm test
deploy:
  provider: heroku
  app: gfw-geostore-api
  api_key:
    secure: PT3U+kzvXHMyTru7SEnRRy7YuA4Btp7CpT/pKXop8Ldf4/TZ2QJTsMRbDB1UO9qAtwpn0TtyDoIDXeIBcrecLWKOi7S+lOpmD/fK0bJY4nBZtklQLJIX1mpxlMHwAHzXuCWg2BSVM4tD7DQiXDYxHze1aeFCHvolK1HNV4bLflB8AWDdSQBH9jIROWUveqpZP/izh6lVJ35P9zOwdLupbWgmza1hpjS1paxAeqlD/sT/vhosC90Zmrob2FoOZvXUdRBshXin6e6hzp+wfQLd65bH9ZvVGdnNu533bbP790n3nnUSh3Aca/dDKFweL291rAEFjoZuzPE9TrgakiQ1woqePy6fwMn/RTlmHVZTd+r1z0pc0WWvYgublTSCzGOAj4NCGFvEnaoOYBKpsePUf5O5aHN5/eQfBeH5U6HIjBgyUuxoxUAZ6kQVhyH+yWq2/J5UkY4AZ81qz+FJniztnITCKhLv82Hm/7RJMGDfn7bGci3vPnJyv/QBdiF+gUDlFOUvIXmJqek9rGkLtfohoxk/WWX2LVOr/VyNdYbLeDcciOGvyxw0trRhyLbA/mnL3TDYF0d1RCULhVjZ8w32s6oDA+TM6WKKo/8HSOHuYIk6jkfsU6xXSbhZHXBLex1kn3uObm5pqhR1mPB57MxqUnaFkr39W+UCVpO/M22b2Xc=
