language: node_js
node_js:
- 5.7.0
sudo: required
services:
- docker
script:
- docker-compose -f docker-compose-test.yml build
- docker-compose -f docker-compose-test.yml run test
addons:
  ssh_known_hosts: $DEPLOY_HOST
before_install:
- openssl aes-256-cbc -K $encrypted_0f765e1d606f_key -iv $encrypted_0f765e1d606f_iv
  -in deploy-key.enc -out deploy-key -d
- bash _scripts/install.sh
after_success:
- bash _scripts/deploy.sh
env:
  global:
  - secure: QAfnbHwGASVch9ngGXiRIzWWjgMtXKnt4Cr0svxIAt1yQCZ9VhYmA2VkGFexDfyA/x+VRVCZuFE2ajcBIfIGnOdl5EbhAi9bF0f5mFsn27kBeyeh83mNsRzSfGg+UA9imiMxCflriZUDRoX6CZfQ3uKIFCWAmf0N1vrN8AJYplaGT2XUULJ0XAl1cQCFeXWiPH50h7NdOvMM1WqQ3iXb9cvbh+JeBfDIj29KEu28/BUFaSXnYocvHq1Dhia/4jueOc2495Fzs7PG3+qvTMuWieu70ue/uFRS6E8x5YnpBH10ZBxqSXYjSxdjQzyIehxe6xfVhsmBd+WfbAD/ehCkt3CRaKK51uqMSd/xc/gWWotm3jRzC8sLh1CnSZqeLaNoN7/XiFlsS2w8a5vhaPHhK5Vzr+liXBrboA116PrP9bnxglCYLXC8pjPp2R8tHML2myKxYaRj+HL0eCdPfxw06Q5i9MVik72l5psF6HisPY1s3oec/boUJfWMnnk6NSI2RCRYcJHDJslOXNY0EPUrHlhLCJZ7LlnKZB/ah8RXs0B1hXcX+l995rHuGiyl860T3XxeKqcIlpgj/+j2POsHONfCJHjpFU6XqWsz3Dr06pFxQewvYX01fM9yVphHpZeH1Bo7pYK4YKoNLAsVGJCqkmKmXTY6R0k5kw6XSF3BelU=
  - secure: OhoVoXZr3IHJwDcSMIMTOaXDSvaJvXPb/72NXjXEzDv1Y05RlFAc+WfLN3/ZEqrpUpAU8+tr1hd1/h9EbAFr3+rsdC9a3VcR5Hzext3VnZ+1/ysiKs0vgV/QpuaI2GgRUHzazleg6aj05HQXO0qcv7fRtIfLWfx6eDDBwU/TkRh+YQZ558oAQhnb+iLxXtbB0VXwSi9TNhISj34ki86zt4YE8HlCmq+e6tY8fermvQuAbYYgPr0T0Yj6BIRxStUgsf5cugWN3BZHeAGl+uRLx24Ea1TZDyQimhhRnOHjKdGXTKYHU/v5q68HA8zsdLGjviE4WQlWj1mxFUYBZrsBWylklYK2cnZHFk4M5KyLnsMasKW0NnHJO1cjzMbw2knUOMMLxUD5OtyMj0ianlmJ2o0UJ8ykCaKN5tQfWlyrn+2PfQNvonrcBt4Jwn6HHNzGk5a7L8NwShzgSaqks32fXLRTBs34AXD07Gy8kRbUV9BKaiEiRBw5rl7ed0dK8jqkZb8YIprVUvggpCD0EmRbPXDXn4SDKJDMdslzXsE3Yoy8cru1BZVePO1qM6o1622bHxmBjPipPTGkSO0BMjwbs2aT/xb1rEMtiX3kBLUecKKaUWByxf263D0wSak6qX8IA0VLKz0EiFK1MgEnrHMc44mIWQNoFUzXDteYUV1pGYU=
  - secure: q+TPzLpBd0v4iGq0QMSKOGUnqfGg0n3q4rrF4u91sJBAjReckTr6lB4X2u0R+hcAA8vBnFdtqGgeAvpDWKJgXrkIYkmxOB13LyvBsA3KNSrzm04goZ3Ik44WJ6l/xJXQPlNE+t3Gl7Zd6k1z7mWV+e+QIMTfO5Ue9i51V/9RZlpfd0SMSQNzzX+qActjDpmn4aS730VWECj8Q2NbVoPh29ZlW7gUJbMUFbVZ4LV6nZO0WjmP6wlq4RT5SIDTS3i1gfq4W5iw+VxW0MN0QpYIOwitvuzXMcvKLlPzXPB6YsEQzqEvTR0nEGzJ+QZiDkqNHztpqMIPZuYT0KY8MIdrOYC1prvMvUlRCLZGKAIiuXfsT3S3ztFuG3tu8vNW0oCkG8+w+a34VEAyWgJaRfyngNiGpvWBuIuoH+lS+R5tAnNA0ctgRYLoeuM6Dyb1f6L1yc5nq6lUI5IiHCw1lSLMnOav3fArT0XMJ7pVeqez2BUF9sEeHtltT7NrWj6QrxbzLXn7dRBn5vVu3cwQx4RM7l95lZc16M3yaJ+irYrDrthOmqb2Ks+uKiJ8ftF7T/y8+2DWu0RfbDzb9Xhfq50BBOZocv4+tkKjxGyESSoCGN6HW0yrKiHry4kF1DCvPMIgs6TovTIK8jKA8FWBpqpbfZB0xs1ihucns40vrV2vIXI=
