language: node_js
node_js:
  - 5.7.0
sudo: required
services:
  - docker
script:
  - docker-compose -f docker-compose-test.yml build
  - docker-compose -f docker-compose-test.yml run test
addons:
  ssh_known_hosts: $DEPLOY_HOST
before_install:
  - bash _scripts/install.sh
after_success:
  - bash _scripts/deploy.sh
