prod:
  image: vizzuality/gfw-geostore-api:1.1.0${STAGING}
  ports:
    - "3100"
  env_file:
    - prod.env
  command: start
  restart: always
  dns: ${DNS_SERVER}
  # log_driver: "gelf"
  # log_opt:
  #   gelf-address: ${GELF_ADDRESS}
