develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35731:35729"
  container_name: gfw-geostore-api-develop
  environment:
    NODE_ENV: dev
    CARTODB_USER: wri-01
    CT_URL: http://mymachine:9000
    LOCAL_URL: http://mymachine:4100
  command: develop
  links:
    - mongo
  volumes:
    - ./app:/opt/gfw-geostore-api/app
mongo:
  image: mongo
  container_name: gfw-geostore-mongo
  command: --smallfiles
  ports:
    - "27017"
  volumes:
    - $HOME/docker/data/gfw-geostore-api:/data/db
  restart: always
