prod:
  image: vizzuality/gfw-geostore-api:1.2.0${STAGING}
  ports:
    - "3100"
  env_file:
    - prod.env
  command: start
  restart: always
  dns: ${DNS_SERVER}
  log_driver: "syslog"
  log_opt:
    gelf-address: ${SYSLOG_ADDRESS}
    tag: "{{.ImageName}}${STAGING}"
