prod:
  image: vizzuality/gfw-geostore-api:1.0.0${STAGING}
  ports:
    - "3100"
  env_file:
    - prod.env
  command: start
  restart: always
  log_driver: "syslog"
  log_opt:
    syslog-address: ${SYSLOG_ADDRESS}
    tag: rw-dataset${STAGING}
