test:
  extends:
    file: base.yml
    service: base
  ports:
    - "3100"
  container_name: gfw-geostore-api-test
  environment:
    NODE_ENV: test
  command: test
  links:
    - mongo
mongo:
  image: mongo
  command: --smallfiles
  ports:
    - "27017"
  restart: always
